version: "3.2"
services:
  front:
    image: front.image:latest
    build: ./
    ports:
    - 3000:3000
    expose:
    - "3000"
    restart: always
    environment:
        NODE_ENV: production
        PORT: 3000
        HOST: 0.0.0.0